apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: identity2
  annotations:
    backstage.io/kubernetes-id: identity
    app.kubernetes.io/name: identity
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
