apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-15T20:59:45Z"
  name: tiller
  namespace: kube-system
  resourceVersion: "665974"
  uid: 82c7526b-aab5-4d61-aec6-f9536203289a
